on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
name: Release
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1
      - name: apt-get update
        run: sudo apt-get update
      - name: flutter build
        run: flutter build apk --release
      - name: Rename apk
        working-directory: build/app/outputs/apk/release
        run: mv app-release.apk CheckList.apk
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/apk/release/CheckList.apk
